#!/usr/bin/env bash
set -euo pipefail

# claude-email-hook installer
# Interactive setup → generates config.yaml → deploys hooks

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_FILE="$SCRIPT_DIR/config.yaml"
HOOKS_DIR="$HOME/.claude/hooks"
SETTINGS_FILE="$HOME/.claude/settings.json"
CLAUDE_MD="$HOME/CLAUDE.md"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${BLUE}[info]${NC} $1"; }
ok()    { echo -e "${GREEN}[ok]${NC} $1"; }
warn()  { echo -e "${YELLOW}[warn]${NC} $1"; }
err()   { echo -e "${RED}[error]${NC} $1"; }

header() {
    echo ""
    echo -e "${CYAN}╔══════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║     claude-email-hook installer      ║${NC}"
    echo -e "${CYAN}╚══════════════════════════════════════╝${NC}"
    echo ""
}

# ─── Checks ───

check_deps() {
    local missing=0

    if ! command -v python3 &>/dev/null; then
        err "python3 not found"
        missing=1
    fi

    if ! command -v msmtp &>/dev/null; then
        err "msmtp not found. Install it first:"
        echo "  Ubuntu/Debian: sudo apt install msmtp"
        echo "  macOS: brew install msmtp"
        echo "  Arch: sudo pacman -S msmtp"
        missing=1
    fi

    if ! command -v claude &>/dev/null; then
        warn "claude CLI not found. Summary generation requires it."
    fi

    if ! python3 -c "import jinja2" &>/dev/null; then
        err "Jinja2 not found. Install it:"
        echo "  pip install jinja2"
        missing=1
    fi

    if ! python3 -c "import yaml" &>/dev/null; then
        err "PyYAML not found. Install it:"
        echo "  pip install pyyaml"
        missing=1
    fi

    if [ "$missing" -eq 1 ]; then
        echo ""
        err "Missing dependencies. Please install them and re-run."
        exit 1
    fi

    ok "All dependencies found"
}

# ─── Provider Selection ───

select_provider() {
    echo ""
    info "Select your email provider:"
    echo ""
    echo "  1) 126 (网易)"
    echo "  2) QQ Mail"
    echo "  3) Gmail"
    echo "  4) Outlook / Office365"
    echo "  5) Custom SMTP"
    echo ""
    read -rp "Choose [1-5]: " choice

    case "$choice" in
        1) PROVIDER="126" ;;
        2) PROVIDER="qq" ;;
        3) PROVIDER="gmail" ;;
        4) PROVIDER="outlook" ;;
        5) PROVIDER="custom" ;;
        *) err "Invalid choice"; exit 1 ;;
    esac

    ok "Provider: $PROVIDER"
}

# ─── SMTP Credentials ───

get_smtp_credentials() {
    echo ""
    read -rp "Sender email address: " SMTP_USER
    echo ""

    case "$PROVIDER" in
        126) info "Log into mail.126.com → Settings → POP3/SMTP/IMAP → Enable SMTP → Get authorization code" ;;
        qq)  info "Log into mail.qq.com → Settings → Account → Enable SMTP → Get authorization code" ;;
        gmail) info "Go to myaccount.google.com → Security → 2FA → App passwords → Create one" ;;
        outlook) info "Use your regular password, or create an app password if 2FA is enabled" ;;
    esac

    echo ""
    read -rsp "SMTP password / authorization code: " SMTP_PASSWORD
    echo ""
    ok "Credentials saved"
}

# ─── Custom SMTP ───

get_custom_smtp() {
    echo ""
    read -rp "SMTP host: " CUSTOM_HOST
    read -rp "SMTP port [465]: " CUSTOM_PORT
    CUSTOM_PORT="${CUSTOM_PORT:-465}"
    read -rp "Use STARTTLS? (y/n) [n]: " CUSTOM_STARTTLS
    if [[ "$CUSTOM_STARTTLS" =~ ^[yY] ]]; then
        CUSTOM_TLS_STARTTLS="on"
    else
        CUSTOM_TLS_STARTTLS="off"
    fi
}

# ─── Notification Config ───

get_notification_config() {
    echo ""
    info "Realtime notifications (Email A)"
    echo "  Sent immediately when Claude Code finishes a task or needs your attention."
    echo ""
    read -rp "Realtime notification recipient email: " REALTIME_TO

    echo ""
    info "Daily digest (Email B) - optional"
    echo "  Aggregated daily summary of all Claude Code activity."
    echo ""
    read -rp "Enable daily digest? (y/n) [n]: " DIGEST_ENABLED

    DIGEST_TO=""
    DIGEST_CRON="0 20 * * *"

    if [[ "$DIGEST_ENABLED" =~ ^[yY] ]]; then
        DIGEST_ENABLED="true"
        read -rp "Digest recipient email: " DIGEST_TO
        read -rp "Digest send time (cron format) [0 20 * * *]: " DIGEST_CRON_INPUT
        DIGEST_CRON="${DIGEST_CRON_INPUT:-$DIGEST_CRON}"
        ok "Digest enabled: $DIGEST_TO at cron($DIGEST_CRON)"
    else
        DIGEST_ENABLED="false"
    fi
}

# ─── Tracker Config ───

get_tracker_config() {
    echo ""
    read -rp "Enable project tracker? (y/n) [y]: " TRACKER_ENABLED
    if [[ "$TRACKER_ENABLED" =~ ^[nN] ]]; then
        TRACKER_ENABLED="false"
    else
        TRACKER_ENABLED="true"
    fi
}

# ─── Generate config.yaml ───

generate_config() {
    cat > "$CONFIG_FILE" << EOF
# claude-email-hook configuration
# Generated by install.sh on $(date '+%Y-%m-%d %H:%M:%S')

smtp:
  provider: "$PROVIDER"
  user: "$SMTP_USER"
  password: "$SMTP_PASSWORD"

notifications:
  realtime:
    to: "$REALTIME_TO"
    events:
      - "Stop"
      - "Notification"
  digest:
    enabled: $DIGEST_ENABLED
    to: "$DIGEST_TO"
    cron: "$DIGEST_CRON"

summary:
  model: "claude-haiku-4-5-20251001"

tracker:
  enabled: $TRACKER_ENABLED
EOF

    chmod 600 "$CONFIG_FILE"
    ok "Config written to $CONFIG_FILE"
}

# ─── Configure msmtp ───

configure_msmtp() {
    local MSMTPRC="$HOME/.msmtprc"

    # Load provider settings
    if [ "$PROVIDER" = "custom" ]; then
        SMTP_HOST="$CUSTOM_HOST"
        SMTP_PORT="$CUSTOM_PORT"
        TLS_STARTTLS="$CUSTOM_TLS_STARTTLS"
    else
        SMTP_HOST=$(python3 -c "import yaml; d=yaml.safe_load(open('$SCRIPT_DIR/providers/$PROVIDER.yaml')); print(d['host'])")
        SMTP_PORT=$(python3 -c "import yaml; d=yaml.safe_load(open('$SCRIPT_DIR/providers/$PROVIDER.yaml')); print(d['port'])")
        TLS_STARTTLS=$(python3 -c "import yaml; d=yaml.safe_load(open('$SCRIPT_DIR/providers/$PROVIDER.yaml')); print(d['tls_starttls'])")
    fi

    # Backup existing config
    if [ -f "$MSMTPRC" ]; then
        cp "$MSMTPRC" "$MSMTPRC.bak.$(date +%s)"
        warn "Existing ~/.msmtprc backed up"
    fi

    cat > "$MSMTPRC" << EOF
defaults
auth           on
tls            on
tls_starttls   $TLS_STARTTLS
tls_trust_file /etc/ssl/certs/ca-certificates.crt
logfile        ~/.msmtp.log

account        claude-email-hook
host           $SMTP_HOST
port           $SMTP_PORT
from           $SMTP_USER
user           $SMTP_USER
password       $SMTP_PASSWORD

account default : claude-email-hook
EOF

    chmod 600 "$MSMTPRC"
    ok "msmtp configured at $MSMTPRC"
}

# ─── Deploy hooks ───

deploy_hooks() {
    mkdir -p "$HOOKS_DIR"

    # Copy source files
    cp "$SCRIPT_DIR/src/common.py" "$HOOKS_DIR/"
    cp "$SCRIPT_DIR/src/notify.py" "$HOOKS_DIR/"
    cp "$SCRIPT_DIR/src/digest.py" "$HOOKS_DIR/"
    mkdir -p "$HOOKS_DIR/templates"
    cp "$SCRIPT_DIR/src/templates/notify.html" "$HOOKS_DIR/templates/"
    cp "$SCRIPT_DIR/src/templates/digest.html" "$HOOKS_DIR/templates/"

    # Symlink config so scripts can find it
    ln -sf "$CONFIG_FILE" "$HOOKS_DIR/config.yaml"

    chmod +x "$HOOKS_DIR/notify.py" "$HOOKS_DIR/digest.py"

    ok "Hook scripts deployed to $HOOKS_DIR"
}

# ─── Register hooks in settings.json ───

register_hooks() {
    if [ ! -f "$SETTINGS_FILE" ]; then
        warn "~/.claude/settings.json not found, creating"
        echo '{}' > "$SETTINGS_FILE"
    fi

    # Use python to safely merge hooks into settings.json
    python3 << 'PYEOF'
import json

settings_path = "$SETTINGS_FILE".replace("$SETTINGS_FILE", "")
# Re-read the actual path
import os
settings_path = os.path.expanduser("~/.claude/settings.json")
hooks_dir = os.path.expanduser("~/.claude/hooks")

with open(settings_path, "r") as f:
    settings = json.load(f)

notify_cmd = f"python3 {hooks_dir}/notify.py"

settings["hooks"] = {
    "Stop": [{"matcher": "", "hooks": [{"type": "command", "command": notify_cmd}]}],
    "Notification": [{"matcher": "", "hooks": [{"type": "command", "command": notify_cmd}]}],
}

with open(settings_path, "w") as f:
    json.dump(settings, f, indent=2, ensure_ascii=False)
    f.write("\n")
PYEOF

    ok "Hooks registered in settings.json"
}

# ─── Setup tracker ───

setup_tracker() {
    if [ "$TRACKER_ENABLED" = "false" ]; then
        return
    fi

    local TRACKER_FILE="$HOOKS_DIR/project_tracker.md"
    if [ ! -f "$TRACKER_FILE" ]; then
        cp "$SCRIPT_DIR/tracker/project_tracker.md" "$TRACKER_FILE"
        ok "Project tracker initialized at $TRACKER_FILE"
    else
        info "Project tracker already exists, keeping it"
    fi

    # Inject CLAUDE.md snippet
    local SNIPPET="$SCRIPT_DIR/tracker/CLAUDE.md.snippet"
    local MARKER="## Project Tracker (claude-email-hook)"

    if [ -f "$CLAUDE_MD" ] && grep -qF "$MARKER" "$CLAUDE_MD"; then
        info "Tracker instructions already in ~/CLAUDE.md"
    else
        if [ -f "$SNIPPET" ]; then
            echo "" >> "$CLAUDE_MD"
            cat "$SNIPPET" >> "$CLAUDE_MD"
            ok "Tracker instructions added to ~/CLAUDE.md"
        fi
    fi
}

# ─── Setup cron ───

setup_cron() {
    if [ "$DIGEST_ENABLED" != "true" ]; then
        return
    fi

    local CRON_CMD="cd $SCRIPT_DIR && python3 src/digest.py"
    local CRON_MARKER="# claude-email-hook digest"

    # Remove old entry if exists
    (crontab -l 2>/dev/null || true) | grep -v "$CRON_MARKER" | crontab -

    # Add new entry
    (crontab -l 2>/dev/null || true; echo "$DIGEST_CRON $CRON_CMD $CRON_MARKER") | crontab -

    ok "Cron job set: $DIGEST_CRON"
}

# ─── Test email ───

test_email() {
    echo ""
    read -rp "Send a test email to $REALTIME_TO? (y/n) [y]: " DO_TEST
    if [[ "$DO_TEST" =~ ^[nN] ]]; then
        return
    fi

    echo '{"hook_event_name":"Stop","session_id":"test-install","cwd":"'$SCRIPT_DIR'","transcript_path":""}' \
        | python3 "$HOOKS_DIR/notify.py"

    if [ $? -eq 0 ]; then
        ok "Test email sent! Check your inbox."
    else
        warn "Test email may have failed. Check ~/.msmtp.log for details."
    fi
}

# ─── Summary ───

show_summary() {
    echo ""
    echo -e "${CYAN}════════════════════════════════════════${NC}"
    echo -e "${GREEN}  Installation complete!${NC}"
    echo -e "${CYAN}════════════════════════════════════════${NC}"
    echo ""
    echo "  Config:     $CONFIG_FILE"
    echo "  Hooks:      $HOOKS_DIR/"
    echo "  msmtp:      ~/.msmtprc"
    echo ""
    echo "  Realtime → $REALTIME_TO"
    if [ "$DIGEST_ENABLED" = "true" ]; then
        echo "  Digest   → $DIGEST_TO (cron: $DIGEST_CRON)"
    fi
    if [ "$TRACKER_ENABLED" = "true" ]; then
        echo "  Tracker:    $HOOKS_DIR/project_tracker.md"
    fi
    echo ""
    echo "  To reconfigure: edit $CONFIG_FILE and re-run ./install.sh"
    echo "  To uninstall:   ./uninstall.sh"
    echo ""
}

# ─── Main ───

main() {
    header

    # If config.yaml exists, offer to reuse
    if [ -f "$CONFIG_FILE" ]; then
        info "Existing config.yaml found"
        read -rp "Re-deploy from existing config? (y=redeploy / n=reconfigure) [y]: " REUSE
        if [[ ! "$REUSE" =~ ^[nN] ]]; then
            # Load values from existing config
            PROVIDER=$(python3 -c "import yaml; d=yaml.safe_load(open('$CONFIG_FILE')); print(d['smtp']['provider'])")
            SMTP_USER=$(python3 -c "import yaml; d=yaml.safe_load(open('$CONFIG_FILE')); print(d['smtp']['user'])")
            SMTP_PASSWORD=$(python3 -c "import yaml; d=yaml.safe_load(open('$CONFIG_FILE')); print(d['smtp']['password'])")
            REALTIME_TO=$(python3 -c "import yaml; d=yaml.safe_load(open('$CONFIG_FILE')); print(d['notifications']['realtime']['to'])")
            DIGEST_ENABLED=$(python3 -c "import yaml; d=yaml.safe_load(open('$CONFIG_FILE')); print(str(d['notifications']['digest'].get('enabled', False)).lower())")
            DIGEST_TO=$(python3 -c "import yaml; d=yaml.safe_load(open('$CONFIG_FILE')); print(d['notifications']['digest'].get('to', ''))")
            DIGEST_CRON=$(python3 -c "import yaml; d=yaml.safe_load(open('$CONFIG_FILE')); print(d['notifications']['digest'].get('cron', '0 20 * * *'))")
            TRACKER_ENABLED=$(python3 -c "import yaml; d=yaml.safe_load(open('$CONFIG_FILE')); print(str(d.get('tracker', {}).get('enabled', True)).lower())")

            configure_msmtp
            deploy_hooks
            register_hooks
            setup_tracker
            setup_cron
            test_email
            show_summary
            return
        fi
    fi

    check_deps
    select_provider

    if [ "$PROVIDER" = "custom" ]; then
        get_custom_smtp
    fi

    get_smtp_credentials
    get_notification_config
    get_tracker_config
    generate_config
    configure_msmtp
    deploy_hooks
    register_hooks
    setup_tracker
    setup_cron
    test_email
    show_summary
}

main "$@"
